#!/bin/bash

echo "🔍 Checking Railway Environment Requirements"
echo "=============================================="
echo ""

echo "📋 Required Environment Variables:"
echo ""
echo "✅ Backend Service:"
echo "   SUPABASE_URL=your_supabase_url"
echo "   SUPABASE_ANON_KEY=your_anon_key"
echo "   SUPABASE_SERVICE_ROLE_KEY=your_service_role_key"
echo "   CORS_ORIGINS=https://terrafoma-production.up.railway.app,http://localhost:3001"
echo "   PYTHONUNBUFFERED=1"
echo ""
echo "⚡ Optional (for GEE features):"
echo "   GEE_SERVICE_ACCOUNT_EMAIL=your-gee@project.iam.gserviceaccount.com"
echo ""
echo "✅ Frontend Service:"
echo "   NEXT_PUBLIC_API_URL=https://terrafoma-production-1c7c.up.railway.app"
echo "   NEXT_PUBLIC_MAPBOX_TOKEN=your_mapbox_token"
echo "   PORT=3000"
echo "   NODE_ENV=production"
echo ""
echo "📊 Railway Dashboard Steps:"
echo "1. Go to railway.app → Your Project"
echo "2. Click on Backend Service → Variables tab"
echo "3. Add each variable above"
echo "4. Backend will automatically redeploy"
echo "5. Wait 3-5 minutes for build to complete"
echo ""
echo "🔍 Check Deployment Status:"
echo "   Railway Dashboard → Backend Service → Deployments"
echo "   Look for 'Active' status with green checkmark"
echo ""
echo "📝 View Logs:"
echo "   Railway Dashboard → Backend Service → Deployments → Click latest → View Logs"
echo ""
