#!/bin/bash

echo "🔍 Railway Frontend Deployment Troubleshooting"
echo "=============================================
"
echo ""
echo "📊 CRITICAL: Check These Settings in Railway Dashboard"
echo ""
echo "1️⃣  ROOT DIRECTORY (Most Common Issue)"
echo "   Railway Dashboard → Frontend Service → Settings"
echo "   🔥 Root Directory MUST be set to: frontend"
echo "   (Not blank, not /, must be exactly: frontend)"
echo ""
echo "2️⃣  BUILD & START COMMANDS"
echo "   Build Command: npm install && npm run build"
echo "   Start Command: npm run start"
echo ""
echo "3️⃣  ENVIRONMENT VARIABLES (All Required)"
echo "   ✓ NEXT_PUBLIC_API_URL=https://terrafoma-production-1c7c.up.railway.app"
echo "   ✓ NEXT_PUBLIC_MAPBOX_TOKEN=(your token)"
echo "   ✓ PORT=3000"
echo "   ✓ NODE_ENV=production"
echo ""
echo "4️⃣  CHECK DEPLOYMENT LOGS"
echo "   Railway Dashboard → Frontend Service → Deployments → Latest"
echo "   Click 'View Logs' to see actual error"
echo ""
echo "🔧 Common Fixes:"
echo ""
echo "Issue: 'Cannot find package.json'"
echo "Fix: Set Root Directory to 'frontend'"
echo ""
echo "Issue: 'ENOENT: no such file or directory'"
echo "Fix: Verify Root Directory is exactly 'frontend' (no leading/trailing spaces)"
echo ""
echo "Issue: 'Module not found' or 'Cannot find module'"
echo "Fix: Check build logs - may need to clear Railway cache"
echo ""
echo "Issue: 'Port 3000 already in use'"
echo "Fix: Railway auto-assigns PORT - use: npm start (not npm run dev)"
echo ""
echo "🚀 Quick Fix Steps:"
echo "1. Railway → Frontend Service → Settings"
echo "2. Scroll to 'Root Directory'"
echo "3. Enter: frontend"
echo "4. Click 'Update Root Directory'"
echo "5. Go to Deployments → Click '...' → Redeploy"
echo "6. Wait 2-3 minutes"
echo "7. Check logs for errors"
echo ""
echo "📝 Get Logs:"
echo "   curl https://terrafoma-production.up.railway.app"
echo "   (Will show 502 if not running, or actual page if working)"
echo ""
